feat(dependabot-merge): update PR with merge attempt result

diff --git a/dependabot-merge/action.yml b/dependabot-merge/action.yml
--- a/dependabot-merge/action.yml
+++ b/dependabot-merge/action.yml
@@ -30,30 +30,45 @@ runs:
       id: bootstrap
       shell: bash
       run: |
-        function mergeable() {
-          if [[ "${{ steps.changes.outputs.any_changed }}" != "true" ]]
+        function is_dependabot_pr() {
+          if [[ "${{ github.event.client_payload.detail.pull_request }}" != "" \
+            && "${{ github.event.client_payload.base.actor }}" == "dependabot[bot]" \
+            && "${{ github.event.client_payload.base.ref }}" == dependabot* ]]
           then
+            return 0
+          else
             return 1
           fi
-          local update_type=${1/version-update:/}
-          case "$update_type" in
-          ${{ inputs.automerge_level }}) return 0;;
-          *) return 1;;
-          esac
         }
-        if [[ "${{ github.event.client_payload.detail.pull_request }}" != "" && "${{ github.event.client_payload.base.actor }}" == "dependabot[bot]" ]]
-        then
+        function mergeable() {
+          if is_dependabot_pr; then
+            if [[ "${{ steps.changes.outputs.any_changed }}" != "true" ]]
+            then
+              return 1
+            fi
+            local update_type=${1/version-update:/}
+            case "$update_type" in
+            ${{ inputs.automerge_level }}) return 0;;
+            *) return 1;;
+            esac
+          else
+            return 1
+          fi
+        }
+
+        if is_dependabot_pr; then
           echo "is_dependabot_pr=true"  >> "$GITHUB_OUTPUT"
         else
           echo "is_dependabot_pr=false"  >> "$GITHUB_OUTPUT"
         fi
-        # shellcheck disable=SC2091
+
         if mergeable "${{ github.event.client_payload.detail.dependabot_update_type }}"
         then
           echo "automerge=true" >> "$GITHUB_OUTPUT"
         else
           echo "automerge=false" >> "$GITHUB_OUTPUT"
         fi
+
     - name: Generate Summary
       id: summary
       shell: bash
@@ -67,6 +82,8 @@ runs:
         }
 
         {
+          echo ":dependabot: Attempt Merge: ${{ steps.bootstrap.outputs.automerge }}"
+          echo ""
           echo "| Decision Table | Value |";
           echo "| ------ | ------ |"
           echo "|job_id| ${{ github.job }} |"
@@ -90,21 +107,56 @@ runs:
       with:
         issue_number: ${{ github.event.client_payload.detail.pull_request }}
         body: |
-          :dependabot: Attempt Merge: ${{ steps.bootstrap.outputs.automerge }}
-
           ${{ steps.summary.outputs.comment }}
         token: ${{ inputs.token }}
         search_term: "dependabot-automerge-status ${{ inputs.change_filter }}"
-    - name: Dependabot Merge
-      continue-on-error: true
+    - name: Merge
+      uses: nick-fields/retry@7152eba30c6575329ac0576536151aca5a72780e # v3.0.0
+      id: merge
       if: |
-        startsWith(github.event.client_payload.base.ref, 'dependabot') &&
-        steps.bootstrap.outputs.is_dependabot_pr == 'true' &&
-        steps.changes.outputs.any_changed  == 'true' &&
         steps.bootstrap.outputs.automerge == 'true'
-      shell: bash
       env:
         GITHUB_TOKEN: ${{ inputs.token }}
+      with:
+        shell: bash
+        max_attempts: 2
+        retry_wait_seconds: 30
+        timeout_seconds: 30
+        retry_on: error
+        command: |
+          gh pr review --approve "${{ github.event.client_payload.detail.pull_request }}"
+          gh pr merge -s "${{ github.event.client_payload.detail.pull_request }}"
+    - name: PR Result Comment
+      id: merge_result
+      if: |
+        steps.bootstrap.outputs.automerge == 'true'
+      shell: bash
       run: |
-        gh pr review --approve "${{ github.event.client_payload.detail.pull_request }}"
-        gh pr merge -s "${{ github.event.client_payload.detail.pull_request }}"
+        eof=$(head -c15 /dev/urandom | base64)
+        {
+          printf "comment<<%s\n" "${eof}";
+          if [[ "${{ steps.merge.outcome }}" == "success" ]]
+          then
+            echo ":dependabot: Merge Success :thumbsup:"
+          else
+            echo ":dependabot: Merge Failed :cry:"
+            echo ""
+            echo "Attempted to merge ${{ steps.merge.outputs.total_attempts}} time(s) but failed."
+            echo ""
+            echo "The final exit code from the step was ${{ steps.merge.outputs.exit_code }}."
+            echo "${{ steps.merge.outputs.exit_error }}"
+          fi
+          printf "%s\n" "${eof}";
+        } >> "$GITHUB_OUTPUT"
+    - name: Update PR
+      id: report
+      if: |
+        (success() || failure()) &&
+        steps.bootstrap.outputs.automerge == 'true'
+      uses: quotidian-ennui/actions-olio/pr-or-issue-comment@main
+      with:
+        issue_number: ${{ github.event.client_payload.detail.pull_request }}
+        body: |
+          ${{ steps.merge_result.outputs.comment }}
+        token: ${{ inputs.token }}
+        search_term: "dependabot-automerge-result ${{ inputs.change_filter }}"
