test: add test of outputs

diff --git a/.github/workflows/test-docker-image-builder.yml b/.github/workflows/test-docker-image-builder.yml
--- a/.github/workflows/test-docker-image-builder.yml
+++ b/.github/workflows/test-docker-image-builder.yml
@@ -42,18 +42,46 @@ jobs:
           dockerfile: docker-image-builder/Dockerfile.test
           image_platforms: linux/amd64
           dockerhub_image_name: ${{ github.repository_owner }}/test-docker-image-builder
+      - name: check outputs
+        id: check_outputs
+        env:
+          DOCKER_LABELS: ${{ steps.docker.outputs.labels }}
+          DOCKER_JSON: ${{ steps.docker.outputs.json }}
+          DOCKER_TAGS: ${{ steps.docker.outputs.image_tags }}
+          DOCKER_VERSION: ${{ steps.docker.outputs.version }}
+        run: |
+          if [[ -z "$DOCKER_TAGS" ]]; then
+            echo "::error::image_tags not set by docker-image-builder"
+            exit 1
+          fi
+          if [[ -z "$DOCKER_LABELS" ]]; then
+            echo "::error::labels not set by docker-image-builder"
+            exit 1
+          fi
+          if [[ -z "$DOCKER_VERSION" ]]; then
+            echo "::error::version not set by docker-image-builder"
+            exit 1
+          fi
+          if [[ -z "$DOCKER_JSON" ]]; then
+            echo "::error::json not set by docker-image-builder"
+            exit 1
+          fi
       - name: Use the image
         id: docker_run
         # bash + curl installed as part of docker-image-builder/Dockerfile.test
+        env:
+          DOCKER_TAGS: ${{ steps.docker.outputs.image_tags }}
         run: |
-          test_image=$(echo "${{ steps.docker.outputs.image_tags }}" | head -n 1 | cut -d' ' -f1)
+          test_image=$(echo "$DOCKER_TAGS" | head -n 1 | cut -d' ' -f1)
           docker run --rm --entrypoint=bash "$test_image" \
             -c "curl -fSsL https://raw.githubusercontent.com/${{ github.repository }}/main/README.md"
       - name: Cleanup
         # Our work here is done, so cleanup
         id: cleanup
         if: success() || failure()
+        env:
+          DOCKER_TAGS: ${{ steps.docker.outputs.image_tags }}
         run: |
-          for image in "${{ steps.docker.outputs.image_tags }}"; do
+          for image in "$DOCKER_TAGS"; do
             docker rmi "$image"
           done
